### ISSUE TITLE
browser.css(...) #=> undefined method `compact' for "(cyclic structure)":String

### ISSUE THREAD

**Issue by ttilberg** [rubycdp/ferrum#73]
Chrome:
Version 81.0.4044.122 (Official Build) (64-bit)

```ruby
require 'ferrum'
b = Ferrum::Browser.new(headless: false)
b.goto 'https://www.npr.org/sections/news/'
b.css('article')

NoMethodError: undefined method `compact' for "(cyclic structure)":String
from /Users/ttilberg/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/ferrum-0.8/lib/ferrum/frame/runtime.rb:189:in `handle_response'
```

I'm getting this error with several (and all) different sites and css strings passing in. Perhaps there is a change in recent versions of Chrome/CDP?

MacOS Mojave 10.14.6
Chrome 81.0.4044.122
Ruby 2.6.5
Ferrum 0.8

**Comment by ttilberg** [comment]
Related https://github.com/rubycdp/ferrum/issues/13

**Comment by wjr1985** [comment]
I’m getting this as well on the majority of sites. Only seemed to appear after upgrading from Ferrum 0.7 to 0.8. Didn’t change Chrome version or anything. Rolling back to Ferrum 0.7 fixed it.

Ubuntu Linux 18.04
Chromium 83.0.4093.0
Ruby 2.5.7
Ferrum 0.8

**Comment by route** [comment]
Hm, I'll investigate later today guys... There's a failing example that's great!

**Comment by route** [comment]
I fixed Ferrum's code that throws the error, but for cycling objects there's nothing Ferrum can do you have to avoid them so instead of getting all `articles` get what you need (content, images inside article, etc) and avoid returning article node because it's cyclic in JS world and cannot be passed to Ruby world.

**Comment by Nakilon** [comment]
I'm porting my thingy from Selenium::Webdriver to Ferrum. It returns lots of nodes from JS but since it returns them in a single object it all becomes `CyclicObject` that is impossible to inspect. I edit the `cycled?` JS, using `JSON.stringify` and currently I suppose it stucks on some `injectedScript` that is by Ferrum and is recursive. Very hard to tell.
I'm debugging it for two days already. I wish there was `CyclicReference` instead of `CyclicObject`, similar to how Ruby's inspection works. Looks like the problem is that JS traversing and Ruby traversing are different processes. JS is capable to detect cycle but this information is needed in Ruby. Also the `reduce_props` looks overcomplicated.

**Comment by Nakilon** [comment]
Maybe the issue will be gone if somehow avoid returning the `injectedScriptId` but I don't understand where it even comes from into the object I return.
